INSERT INTO users
  (
  name, email, password)
VALUES
  ('Hans Xu', 'h_xu@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
  ('Robin Webber', 'rob@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
  ('Oly Girard', 'oly@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

INSERT INTO properties
  (
  title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, provence, city, country, street, post_code)
VALUES (
    'Magic familiar', 'Comfortable fill stick belong fly construction wave positive mean gently happy alone event thousand wore sick rope fighting typical popular nuts built swept particular eye salmon rate explain follow adventure outline dish library heart strength selection pocket teeth production bread everybody luck stage hundred atomic forgotten drove am found forget similar social thousand mass breathe border touch box suit pull into receive felt higher flat question tip slide nearly since branch society herd hurt without ever zoo stuck laugh tomorrow own fall position judge structure new danger mean pig lower steel have weak great either make body long hurry vegetable kept together east straw muscle get broad torn rocket total tribe waste thus careful sentence camera lonely horse doctor spite deeply sudden using rising bag graph pond pine bicycle likely studied rocky near twelve return again film pan dull offer roll effect bone customs wonderful rain gas sets organization bowl coat decide wild remarkable paragraph another check question afternoon helpful climate news bring instrument dozen wing yes aloud stone red eight image door thick us suit particles fall purpose everything perhaps wood basis root difficulty managed safe high dry equal height mainly plain lead grandfather numeral egg attached pleasure shallow did pot closely person right mathematics law tears grandfather driving species forest speech between studying fix twenty lovely brush transportation pink raise coast is grandfather throw exchange fur likely practical apartment massage highest interior slept view vowel weak cave information dug count who political band held top grandmother cause were whenever fed unit expect aid earlier neighborhood series does been certainly simply example cloth thus reach next know right anywhere partly to principle your effect get rhyme minute warn cold finger read dig sweet pride split soon dot hungry taste everything swam crack difficulty closer trunk spend hill consider mother', 128, 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg', 'https://images.pexels.com/photos/1172064/pexels-photo-1172064.jpeg?auto=compress&cs=tinysrgb&h=350', 36317, 1, 3, 0, true, 'Quebec', 'Chicoutimi', 'Canada', '1950 Zujcol Path', '19755');
    INSERT INTO properties (
    title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, provence, city, country, street, post_code) 
    VALUES (
    'List least', 'Younger week student surface speak how sick bark outside combine wide thou improve recent plane soon behavior teacher tape adult pencil remain bear laugh free spin make stick victory picture wheat successful near correctly swept steep lake chapter card film telephone identity brick lucky electricity solar captain rest surprise worth folks caught example larger headed sugar symbol represent handle dot spell straw barn plate among party long fix fifteen had show chain way religious rest afternoon bat accurate behavior bigger term exact hang without him garden yet fur spirit cut bright money plus eight birthday composition soil she minute industrial silk hair herd chief silence temperature thought teacher show signal eye grew deal conversation tank castle energy empty cast carbon care western climate zipper cloth moving lovely shot brush angry ready popular zebra definition grabbed matter leaf picture pipe make paid away refused year service proud balance water fish road massage highway instance yes some doctor board happily here fog plates upon finger secret form fifty sets forth winter bone flag age bottle native whatever should bat farther far local frighten green scientist shoe old finally managed article become equator funny forgot coach happy manner range village baseball tired nuts cat slowly possibly motor develop move found crowd blue aware action may two changing pitch final stick sides sea rear hunt pet handle simple by ought rest machine who spread setting standard too street smallest us extra wear terrible dust ourselves animal underline him unusual contain happily red nearer storm bag ship trouble skin outline pattern among avoid wolf suit brain too doll pig atmosphere warm future society planned nearer lift me storm capital building applied effect cotton share clay report heat around nose sum aware as pot question spend respect equal hill slide independent fully children shorter fed energy', 391, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 34565, 0, 1, 1, true, 'Newfoundland And Labrador', 'Paradise', 'Canada', '1848 Cuzo Trail', '08409'),
    (
    'Prepare if', 'Angry pair does flame factory night sum party trip tomorrow none friend rain quickly generally grew bell row my stairs turn sang possibly having badly over bit inside six industry lonely scientific use he only as long feel instrument worth struggle almost material pilot good roar raw past chief describe join parts welcome feed figure trip settlers partly egg happily have forth bad percent join tobacco writing harder dream series shaking nuts wrong trap actual electric limited join deal hand tape know serve divide sky everyone we snow save mill engineer declared tea proper again earlier strange away aid yet total capital regular pride dream tape example hidden both sense possible earn increase environment area join sand pleasant made hungry throat safety such fighting fruit molecular event thread saw fall clay people stranger chose though citizen state value wild pitch want flower calm nervous silk lovely chosen transportation practice change what occur symbol else thank rose drew central needs proper great twice family shore sink pile clothes character song pocket public unusual chemical canal jar dug together track easily exist organization thou valley ants official accept wide shorter bottle nearby population highest seldom middle weigh anything strength allow guess wore pig cut price special neighborhood nature southern worry properly slow garage religious breath fix dog window human due hurt replied knife gather shop series see sunlight first girl western word vowel look shallow free shout specific alike bell positive deer donkey won union tobacco supper fence discuss seldom possible women science chamber perfect swam principal only elephant tone zero hold instance claws upper hide when anywhere told island aside brown town planet climate layers tribe elephant acres like aware nose jump advice extra thin first flight door stared machinery poetry season climb hand wheat wheat rising fog being tower brick', 184, 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg', 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg?auto=compress&cs=tinysrgb&h=350', 21137, 4, 7, 2, true, 'Ontario', 'Orillia', 'Canada', '1492 Ufimo Junction', '47597'),
    (
    'Roll stranger', 'Observe typical hit organization fruit thumb cost beat numeral chest careful character lose far tent meant thrown traffic movie use golden receive brain rod mood wooden children solve swung though spider smell box put importance afraid touch above smile would refer size good correctly blue duck hunt divide lack whenever further thus organization reach frozen furniture river claws threw catch uncle gray meant lips shout sister pack want trade active wrong value store plural alphabet to police agree make why honor decide rhyme rough new sale come putting remove noted castle object window bridge complete steam sort process opportunity replace basis method hour pine duty inside electricity think surprise go rice nearer fewer hearing soil bite water higher active continent solve beside muscle seeing develop general prize atom musical unusual active appearance cost bean structure zero bus series grew station word organization complete being think make price wish division thing furniture up depend means flew struck correctly paper pond courage brick mouse dull fill official clothes truth morning fun raise cave again wet military live best rhyme author screen afternoon completely should surface tired diameter seat want bare gift glass swim claws lucky highway service leather equal appropriate meat seat window day lady seeing sheet believed battle tax cannot pass universe happily biggest son surrounded generally wish slow loud indicate lead aboard riding pet package settlers blank substance moving golden condition human offer being spend nest iron anybody left play route poem research sky tree wear planet show none hill buy beauty equipment hearing fight type want report aboard consist lesson favorite involved fog toy clear prevent done occasionally grandmother nails shut no simplest block making fifteen trace husband rabbit reach slight classroom accurate fewer monkey shot contrast left pet weak package might sitting you thread pan week gift he', 650, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 5375, 2, 7, 3, true, 'Alberta', 'Edmonton', 'Canada', '1295 Gecado Point', '96594');

    INSERT INTO reservations (
    id, guest_id, property_id, start_date, end_date) 
    VALUES (
    1009999, 743, 114, '2022-09-30', '2022-10-15'),
    (
    1010000, 269, 841, '2021-04-30', '2021-05-18'),
    (
    1010001, 667, 708, '2021-08-22', '2021-08-23');

    INSERT INTO property_reviews (
    guest_id, property_id, reservation_id, rating, message) 
    VALUES (
    328, 190, 1015655, 4, 'Sigkez amafozuz zidak cirazke giikeak lazup cefumzeb ohefcob vugsi vudavi ahevi awogi tagjowos.'),
    (
    340, 769, 1013720, 5, 'Filin alforec pad sevopa ej jesebfuh tap ma ajafihjoc pujawoso kuez zitu sebfal zialuti jool rudpi gogofiri da.'),
    (
    891, 290, 1016559, 3, 'Hawapel pasale udmupnej co uzfos novuhig bilad dedgure vim renfef soumi suti bop.');
